import type { FormResponseData } from "@/features/questionnaire/responseData";

/**
 * Готовый промышленный OT-сценарий для демонстрации: ПЛК, датчик, SCADA, операторская станция,
 * технологическая сеть, подрядчик с VPN, инцидент НСД в OT.
 */
export function getOtIndustrialDemoData(): FormResponseData {
  return {
    department_profile: {
      description:
        "Цех гидравлических линий: АСУ ТП, технологический сегмент OT (VLAN 20), связь с корпоративной сетью через шлюз.",
      manager_name: "И. Петров",
      contact_info: "цех-01@plant.local, вн. 3102",
    },
    assets: [
      {
        id: "plc-l2",
        name: "ПЛК Siemens S7-1515 (линия 2)",
        asset_type: "PLC / контроллер",
        owner: "Группа АСУТП цеха",
        criticality: "high",
        network_zone: "ot_production_vlan20",
        vendor: "Siemens",
        protocols: "Profinet, OPC UA",
        supports_mfa: false,
        supports_patching: false,
        availability_class: "high",
        safety_critical: true,
      },
      {
        id: "sensor-pt-01",
        name: "Датчик давления PT-01 (полевая шина)",
        asset_type: "Датчик / полевое устройство",
        owner: "АСУТП цеха",
        criticality: "medium",
        network_zone: "ot_production_vlan20",
        vendor: "Endress+Hauser",
        protocols: "HART, Profinet",
        supports_mfa: false,
        supports_patching: false,
        availability_class: "medium",
        safety_critical: false,
      },
      {
        id: "hmi-op-01",
        name: "Операторская станция WinCC (линия 2)",
        asset_type: "Операторская станция / HMI",
        owner: "Цех",
        criticality: "high",
        network_zone: "ot_production_vlan20",
        vendor: "Siemens",
        protocols: "OPC UA, RDP (ограниченно)",
        supports_mfa: true,
        supports_patching: false,
        availability_class: "high",
        safety_critical: false,
      },
      {
        id: "scada-01",
        name: "SCADA-сервер цеха",
        asset_type: "SCADA-сервер",
        owner: "Группа АСУТП",
        criticality: "high",
        network_zone: "ot_dmz",
        vendor: "Siemens / Ignition",
        protocols: "OPC UA, Modbus TCP",
        supports_mfa: true,
        supports_patching: true,
        availability_class: "high",
        safety_critical: false,
      },
      {
        id: "net-ot-core",
        name: "Технологический сегмент (L2/L3 OT)",
        asset_type: "Технологическая сеть / сегмент",
        owner: "Сетевой отдел + АСУТП",
        criticality: "critical",
        network_zone: "ot_production_vlan20",
        vendor: "Cisco IE",
        protocols: "Profinet, без прямого доступа из IT",
        supports_mfa: false,
        supports_patching: true,
        availability_class: "critical",
        safety_critical: true,
      },
      {
        id: "gw-ot-it",
        name: "Промышленный шлюз IT↔OT",
        asset_type: "Промышленный шлюз / firewall OT",
        owner: "ИБ + АСУТП",
        criticality: "critical",
        network_zone: "ot_dmz",
        vendor: "Tofino / пром. FW",
        protocols: "OPC UA proxy, фильтрация",
        supports_mfa: false,
        supports_patching: true,
        availability_class: "high",
        safety_critical: false,
      },
      {
        id: "hist-01",
        name: "Historian / сервер телеметрии",
        asset_type: "Historian",
        owner: "Данные производства",
        criticality: "medium",
        network_zone: "ot_dmz",
        vendor: "OSIsoft / аналог",
        protocols: "OPC HDA",
        supports_mfa: true,
        supports_patching: true,
        availability_class: "medium",
        safety_critical: false,
      },
      {
        id: "es-eng-01",
        name: "Инженерная станция TIA Portal",
        asset_type: "Инженерная станция",
        owner: "АСУТП",
        criticality: "high",
        network_zone: "ot_engineering_jump",
        vendor: "Siemens",
        protocols: "Profinet (проектирование)",
        supports_mfa: true,
        supports_patching: true,
        availability_class: "medium",
        safety_critical: false,
      },
      {
        id: "fs-corp-01",
        name: "Корпоративный файловый сервер (IT)",
        asset_type: "Windows Server / файловый сервер",
        owner: "ИТ отдел",
        criticality: "medium",
        network_zone: "corp_lan",
        vendor: "Microsoft",
        protocols: "SMB, Kerberos",
        supports_mfa: true,
        supports_patching: true,
        availability_class: "medium",
        safety_critical: false,
      },
    ],
    business_processes: [
      {
        name: "Непрерывный гидравлический пресс линии 2",
        used_asset_ids: "plc-l2, sensor-pt-01, hmi-op-01, scada-01, net-ot-core",
      },
      {
        name: "Сбор телеметрии и отчёты для MES",
        used_asset_ids: "scada-01, hist-01, gw-ot-it",
      },
    ],
    access_matrix: [
      {
        field_a: "VPN-канал подрядчика «Автоматика-Плюс»",
        field_b: "Доступ к инженерной станции es-eng-01 и операторской hmi-op-01 по согласованию, jump host",
      },
      {
        field_a: "Корпоративная сеть",
        field_b: "Только к gw-ot-it (OPC proxy), прямой доступ к ПЛК запрещён",
      },
    ],
    contractors: [
      {
        field_a: "ООО «Автоматика-Плюс» (интегратор ПЛК)",
        field_b: "Удалённая настройка логики ПЛК по VPN + RDP на jump host; сессии по календарю работ",
      },
    ],
    incidents: [
      {
        field_a: "Несанкционированное подключение в технологическую сеть",
        field_b: "Обнаружен ноутбук в сегменте VLAN 20 без учётной записи; доступ отозван, проведён осмотр шкафов",
      },
    ],
    additional_notes:
      "Демо-сценарий OT: сегментация IT/OT, ограничения MFA/патчинга на ПЛК, компенсирующие меры в отчёте анализа.",
  };
}
